### ISSUE TITLE
Add a check for the minimum version of the FPGA package

### ISSUE THREAD

**Issue by tomtrafford** [PandABlocks/PandABlocks-server#31]
There is an incompatibility between the 3.0 version of the PandA server and earlier versions of the PandA FPGA code due to updates to the extension server. These cause the PandA to freeze after updating the server for a PandA running the FMC_ACQ427 zpkg. 

It would be good if the server could check the version of the FPGA zpkg before it starts.

**Comment by Araneidae** [comment]
I'm going to say that this is _not_ an FPGA compatibility issue, the server is not incompatible with the FPGA.  However, there is an issue with extension server compatibility coupled with an FPGA bug.

This being said, I'm reluctant to couple blocking startup of the server with the top level FPGA version.  During startup of the server we do check that the `*REG` part of the `config_d/registers` file matches what is expected by the server which maintaines its own copy.

Similarly, the kernel driver uses the `*DRV` definitions from the server's `registers` file to define the locations of key registers ... but at present this is _not_ checked during PandA startup.  Unfortunately the kernel driver does not have easy access to this file during loading.

So, thinking aloud here, where can we block startup, and based on what condition?  We want to check the following conditions:

- We would like to check that the `*DRV` registers match the driver's expectations before loading the driver.  This is not done at present.
- We would like to check that the `*REG` definitions match.  This is done, as this information is available to the server during startup.
- This issue is asking for an extra compatibility revision number that will need to be stored somewhere and incremented when necessary to capture compatibility issues.

Don't know what the best route forward is.  My main concern is that I don't want us to have to keep making new releases of the server when this is not necessary.

**Comment by Araneidae** [comment]
It's probably worth documenting the format of the FPGA version number, at least according to the implementation of the `*IDN?` command:
```c
/* The format is four bytes:
 *      customer.major.minor.point
 * where the customer version is only printed if non-zero, and is printed
 * last. */
```
This means that for instance an FPGA version of `0x01020304` will be printed as `2.3.4C1`.
