### ISSUE TITLE
Think of a way to tell the TCP server what 1 clock tick is

### ISSUE THREAD

**Issue by thomascobb** [PandABlocks/PandABlocks-server#8]

**Comment by thomascobb** [comment]
Add a dedicated `*REG` register that counts the currently configured fabric clock for 1 second (using a fixed frequency reference clock) which can be used by the server

**Comment by coretl** [comment]
But this is constantly changing, how can we use this to format TIME fields?

**Comment by tomtrafford** [comment]
2 new: 
*CLOCK.TARGET (User specified clock frequency)
*CLOCK.ACTUAL (Measured clock frequency)
in *REG (Mirrors of SYSTEM registers)
CLOCK_TARGET
CLOCK_ACTUAL

The .state file will need to store time field values in RAW

**Comment by coretl** [comment]
After a conversation with @EdWarrick we wondered if changing `ext_out` `SAMPLES` to `GATE_DURATION` might be more descriptive at the same time as changing it from `UNSCALED` to `SCALED32`. Thoughts?

**Comment by Araneidae** [comment]
That seems a reasonable idea.

**Comment by Araneidae** [comment]
Ok, I will add a new register `*REG.NOMINAL_CLOCK` at register offset 24 with the following definition:
> If this register is non zero the value returned will be used as the reported clock frequency in Hz, otherwise the standard frequency of 125 MHz will be reported and used.

**Comment by coretl** [comment]
> Though hmmm... what about the description now?

How about "Total duration in seconds that GATE was high for each capture"

**Comment by Araneidae** [comment]
The problem with this is that the unscaled value is simply number of samples, as before!

**Comment by coretl** [comment]
I think that it's still fine, the scaled value is what they are requesting to capture, if they choose to get it unscaled they see the raw number of samples and the scale factor to turn it into time in the header

**Comment by Araneidae** [comment]
This should now be addressed by a number of pull requests:
* PR #41 changes scaling of samples
* PR https://github.com/PandABlocks/PandABlocks-FPGA/pull/155 renames `SAMPLES` to `GATE_DURATION`
* PR #42 uses new `*REG.NOMINAL_CLOCK` frequency register
* PR https://github.com/PandABlocks/PandABlocks-FPGA/pull/156 adds `*REG.NOMINAL_CLOCK` to FPGA

Outstanding related issues are:
* Issue #39 is needed so that the saved duration is seconds is retained over server restarts, even if the clock frequency is changed.
* Issue #40 is wanted so that changes to reported clock frequency can be seen.

**Comment by Araneidae** [comment]
This should now be closed by merge 19f58f6d7f40c7d3598bfb33bc1594ce3816fdba.
